<?php

/**
 * @file
 * Contains custom_events.module.
 */

use Drupal\custom_events\Event\UserLoginEvent;

/**
 * Implements hook_user_login().
 */
function custom_events_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);

  // Get the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}
/**
 * Implements hook_node_view().
 */
function custom_events_node_view(&$node, $view_mode, $langcode) {
  // Ensure that the $node is an object and not an array.
  if ($node instanceof \Drupal\node\NodeInterface && $node->getType() === 'movie') {
    // Create the event and dispatch it.
    $event = new \Drupal\custom_events\Event\NodeViewEvent($node);
    \Drupal::service('event_dispatcher')->dispatch(\Drupal\custom_events\Event\NodeViewEvent::EVENT_NAME, $event);
  }
}
